version: "3.8"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: postgres

  adminer:
    image: adminer
    ports:
      - 8080:8080